services:
    db:
        image: mariadb:latest
        environment:
            MARIADB_USER: admin
            MARIADB_DATABASE: chatdb
            MARIADB_ROOT_PASSWORD: rootpassword
            MARIADB_PASSWORD: adminpassword
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - mariadb_network

    backend:
        command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        build: ./api
        volumes:
            - ./api:/app
        ports:
            - "8000:8000"
        networks:
            - mariadb_network
        depends_on:
            - db
        links:
            - "db:db"

    frontend:
        command: "npm run dev --verbose"
        build: ./ui
        volumes:
            - ./ui/src:/app/src
        ports:
            - "4173:4173"
        networks:
            - mariadb_network
        depends_on:
            - backend
        environment:
            - CHOKIDAR_USEPOLLING=true

volumes:
    db_data:

networks:
    mariadb_network:
        driver: bridge
